name = "pstake-webapp"
type = "webpack"
zone_id = '6304918b0989e59de2f10ab7af92840a'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./.next",entry-point = "workers-site"}
compatibility_date = "2022-06-01"

[env.staging]
routes = ['https://staging.frontend-starter-repo.pstake.finance/*']


