name = "persistence-frontend-starter-repo"
compatibility_flags = []
workers_dev = true
site = {bucket = "./out"}
main = "workers-site/index.js"
compatibility_date = "2022-06-06"

[env.staging]
routes = ['https://test-repo.persistence.one/*']


